site_name: Taikun
site_url: http://185.22.98.224
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - abbr
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
    name: material
    favicon: https://media-exp1.licdn.com/dms/image/C4D0BAQFv4jXG3fcf4Q/company-logo_200_200/0/1629111293367?e=2159024400&v=beta&t=8CBazqxwtimxfOs48hTOyxSr0P2wrmx0JHnKVJLFWSs
    logo: https://cloud.tcpro.cz:30100/swift/v1/KEY_121daf025c5742a6844217e262243c65/doc/taikun_icon_white.png
    features:
      - navigation.instant
      - navigation.tabs
      - toc.integrate
      - navigation.expand
      - navigation.sections
      - search.highlight
      - search.share
      - search.suggest
      - navigation.top
      - navigation.tracking
      - navigation.indexes
    palette:
      primary: pink
repo_url: https://github.com/itera-io/taikun-documentation
repo_name: Taikun Documentation

# Page tree
nav:
  - Home: index.md
  - First Steps: first-steps.md
  - Guidelines:
    - Login: guidelines/login.md
    - Change e-mail and password: guidelines/verify-the-e-mail-address-and-change-the-password.md
    - Add cloud credentials: 
      - guidelines/create-credentials/README.md
    - Where to find credentials: guidelines/create-credentials/where-to-find-credentials.md
    - Creating Profiles: guidelines/creating-profiles.md
    - Creating Cluster: guidelines/creating-a-cluster.md
    - Kubeconfigs, Backup, Monitoring, Lock, Reboot: guidelines/backup-monitoring-lock-reboot.md
  - User: 
    - user/README.md
    - Login: user/login.md
    - Dashboard:
      - user/dashboard/README.md
      - Users: user/dashboard/users.md
      - Charts: user/dashboard/charts.md
      - Tables: user/dashboard/tables.md
    - Projects: 
      - user/projects/README.md
      - Project Details: user/projects/project-details.md
      - Kubernetes: user/projects/kubernetes.md
    - My Profie: user/my-profile.md
  - Manager:
    - manager/README.md
    - Login: manager/login.md
    - Dashboard:
      - manager/dashboard/README.md
      - Users: manager/dashboard/users.md
      - Charts: manager/dashboard/charts.md
      - Tables: manager/dashboard/tables.md
    - Projects:
      - manager/projects/README.md
      - Project Details: manager/projects/project-details.md
      - Kubernetes: manager/projects/kubernetes.md
      - Create a New Project: manager/projects/creating-a-new-project.md
    - Flavor Info: manager/flavor-info.md
    - Audit Log: manager/audit-log.md
    - Users: manager/users.md
    - Project Quotas: manager/project-quotas.md
    - Servers: manager/servers.md
    - Taikun Requests: manager/taikun-requests.md
    - Showback Rules: manager/showback-rules.md
    - Showback Summary: manager/showback-summary.md
    - Ticketing: manager/ticketing.md
    - Chargeback: manager/chargeback.md
    - Usage Reports: manager/usage-reports.md
    - Cloud Credentials: manager/cloud-credentials.md
    - Backup Credentials: manager/backup-credentials.md
    - Showback Credentials: manager/showback-credentials.md
    - Kubernetes Profiles: manager/kubernetes-profiles.md
    - Access Profiles: manager/access-profiles.md
    - Alerting Profiles: manager/alerting-profiles.md
    - Policy Profiles: manager/policy-profiles.md
    - Slack Configuration: manager/slack-configuration.md
    - My Profile: manager/my-profile.md
  - Partner:
    - partner/README.md
    - Login: partner/login.md
    - Dashboard:
       - partner/dashboard/README.md
       - Select Organization: partner/dashboard/select-organization.md
       - Users: partner/dashboard/users.md
       - Charts: partner/dashboard/charts.md
       - Tables: partner/dashboard/tables.md
       - Projects: partner/dashboard/projects/README.md
       - Projects Details: partner/dashboard/projects/project-details.md
       - Kubernetes: partner/dashboard/projects/kubernetes.md
       - Create a New Project: partner/dashboard/projects/creating-a-new-project.md
    - Flavor Info: partner/flavor-info.md
    - Audit Log: partner/audit-log.md
    - Users: partner/users.md
    - Project Quotas: partner/project-quotas.md
    - Servers: partner/servers.md
    - Taikun Requests: partner/taikun-requests.md
    - Showback Rules: partner/showback-rules.md
    - Showback Summary: partner/showback-summary.md
    - Ticketing: partner/ticketing.md
    - Chargeback: partner/chargeback.md
    - Usage Reports: partner/usage-reports.md
    - Cloud Credentials: partner/cloud-credentials.md
    - Backup Credentials: partner/backup-credentials.md
    - Billing Credentials: partner/billing-rules.md
    - Showback Credentials: partner/showback-credentials.md
    - Kubernetes Profiles: partner/kubernetes-profiles.md
    - Access Profiles: partner/access-profiles.md
    - Alerting Profiles: partner/alerting-profiles.md
    - Policy Profiles: partner/policy-profiles.md
    - Organizations: partner/organizations.md
    - Billing Rules: partner/billing-credentials.md
    - Slack Configuration: partner/slack-configuration.md
  - Tech Book:
    - LoadBalancer: tech-book/loadbalancers.md
  - Dictionary:
    - Froma A to Z: dictionary/from-a-to-z.md
